import { motion } from "framer-motion";
import { Activity, Target, Layers, Box, AlertCircle, CheckCircle } from "lucide-react";

export default function Metrics({ result }) {
  const confidence = (result.probability * 100).toFixed(2);
  const coverage = (result.coverage * 100).toFixed(2);

  return (
    <div className="relative backdrop-blur-2xl bg-white/[0.03] border border-white/10 p-8 rounded-3xl shadow-2xl overflow-hidden group">
      {/* Subtle Background Glow based on status */}
      <div className={`absolute -top-24 -right-24 w-48 h-48 blur-[80px] rounded-full opacity-20 transition-colors duration-1000 ${result.has_tumor ? 'bg-rose-500' : 'bg-emerald-500'}`} />

      <div className="flex justify-between items-start mb-8">
        <div>
          <h2 className="text-xs font-black uppercase tracking-[0.3em] text-slate-500 mb-1">Neural Analysis</h2>
          <div className="flex items-center gap-2">
            {result.has_tumor ? (
              <AlertCircle className="text-rose-500" size={20} />
            ) : (
              <CheckCircle className="text-emerald-500" size={20} />
            )}
            <span className={`text-2xl font-bold ${result.has_tumor ? "text-rose-400" : "text-emerald-400"}`}>
              {result.has_tumor ? "Positive Detection" : "Negative Detection"}
            </span>
          </div>
        </div>
        <Activity className="text-slate-700 animate-pulse" size={24} />
      </div>

      {/* Main Stats Grid */}
      <div className="grid grid-cols-2 gap-4 mb-8">
        <StatBox 
          icon={<Target size={16} />} 
          label="Confidence" 
          value={`${confidence}%`} 
          color="text-blue-400" 
        />
        <StatBox 
          icon={<Layers size={16} />} 
          label="Coverage" 
          value={`${coverage}%`} 
          color="text-cyan-400" 
        />
        <StatBox 
          icon={<Box size={16} />} 
          label="Tumor Pixels" 
          value={result.tumor_pixels.toLocaleString()} 
          color="text-purple-400" 
        />
        <StatBox 
          icon={<Activity size={16} />} 
          label="Est. Area" 
          value={`${result.tumor_area_cm2} cm²`} 
          color="text-amber-400" 
        />
      </div>

      {/* Probability Progress Section */}
      <div className="space-y-3">
        <div className="flex justify-between text-[10px] font-mono tracking-widest text-slate-400 uppercase">
          <span>AI Probability Index</span>
          <span>{confidence}%</span>
        </div>
        <div className="relative h-4 bg-slate-900/50 rounded-full overflow-hidden border border-white/5 p-[2px]">
          <motion.div
            initial={{ width: 0 }}
            animate={{ width: `${confidence}%` }}
            transition={{ duration: 1.5, ease: "easeOut" }}
            className={`h-full rounded-full relative ${
              result.has_tumor ? "bg-gradient-to-r from-rose-600 to-rose-400" : "bg-gradient-to-r from-emerald-600 to-emerald-400"
            }`}
          >
            {/* Shimmer Effect */}
            <motion.div 
              animate={{ x: ['-100%', '200%'] }}
              transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
              className="absolute inset-0 bg-gradient-to-r from-transparent via-white/30 to-transparent w-1/2"
            />
          </motion.div>
        </div>
      </div>

      <div className="mt-8 pt-6 border-t border-white/5">
        <p className="text-[10px] font-mono text-slate-600 leading-relaxed uppercase">
          Note: This analysis is generated by a Generative Adversarial Network (GAN). 
          Results should be verified by a medical professional.
        </p>
      </div>
    </div>
  );
}

function StatBox({ icon, label, value, color }) {
  return (
    <div className="bg-white/[0.02] border border-white/5 p-4 rounded-2xl hover:bg-white/[0.04] transition-colors">
      <div className="flex items-center gap-2 text-slate-500 mb-2">
        {icon}
        <span className="text-[10px] font-bold uppercase tracking-wider">{label}</span>
      </div>
      <div className={`text-xl font-mono font-semibold ${color}`}>
        {value}
      </div>
    </div>
  );
}